// Automatically generated by gitlab.com/hookactions/gqlgen-relay
// DO NOT EDIT

package model

import (
	"encoding/base64"
	"fmt"

	"github.com/pkg/errors"
	"github.com/vmihailenco/msgpack"
	"gitlab.com/hookactions/gqlgen-relay/relay"
)

// BookEdge is the edge representation of Book
type BookEdge struct {
	Cursor string `json:"cursor"`
	Node   *Book  `json:"node"`
}

// BookConnection is the connection containing edges of Book
type BookConnection struct {
	Edges      []BookEdge     `json:"edges"`
	PageInfo   relay.PageInfo `json:"pageInfo"`
	TotalCount *int           `json:"totalCount"`
}

// BookCursor is the edge representation of Book
type BookCursor struct {
	Offset int    `json:"offset"`
	ID     string `json:"id"`
}

func NewBookCursor(offset int, id fmt.Stringer) *BookCursor {
	return &BookCursor{Offset: offset, ID: id.String()}
}

func EncodeBookCursor(cursor *BookCursor) string {
	b, err := msgpack.Marshal(cursor)
	if err != nil {
		panic("unable to marshal Book cursor: " + err.Error())
	}
	return base64.StdEncoding.EncodeToString(b)
}

func DecodeBookCursor(cursor string) (*BookCursor, error) {
	b, err := base64.StdEncoding.DecodeString(cursor)
	if err != nil {
		return nil, errors.Wrap(err, "unable to decode cursor")
	}

	var out BookCursor
	if err := errors.Wrap(msgpack.Unmarshal(b, &out), "unable to unmarshal Book cursor"); err != nil {
		return nil, err
	}
	return &out, nil
}

func MustDecodeBookCursor(cursor string) *BookCursor {
	decoded, err := DecodeBookCursor(cursor)
	if err != nil {
		panic("unable to decode Book cursor: " + err.Error())
	}
	return decoded
}

var BookInvalidPagination = errors.New("Book invalid pagination parameters")

type BookPaginationFunc = func(offset, limit int) (items []*Book, total *int, err error)

func NewBookPage(defaultLimit int, first *int, afterCursor *string, beforeCursor *string, paginate BookPaginationFunc) (*BookConnection, error) {
	offset := 0
	limit := defaultLimit

	if first != nil {
		limit = *first
	}

	if afterCursor != nil && beforeCursor != nil {
		return nil, BookInvalidPagination
	}

	if afterCursor != nil {
		out, err := DecodeBookCursor(*afterCursor)
		if err != nil {
			return nil, err
		}

		offset = out.Offset + 1
	} else if beforeCursor != nil {
		out, err := DecodeBookCursor(*beforeCursor)
		if err != nil {
			return nil, err
		}

		offset = out.Offset - limit
	}

	page := &BookConnection{}

	items, total, err := paginate(offset, limit)
	if err != nil {
		return nil, err
	}

	for i, item := range items {
		page.Edges = append(page.Edges, BookEdge{
			Cursor: EncodeBookCursor(NewBookCursor(offset+i, item.GetID())),
			Node:   item,
		})
	}

	startCursor, endCursor := (*string)(nil), (*string)(nil)
	if len(page.Edges) > 0 {
		startCursor = relay.NewString(page.Edges[0].Cursor)
		endCursor = relay.NewString(page.Edges[len(page.Edges)-1].Cursor)
	}

	hasNextPage := false
	hasPreviousPage := offset > 0

	if total != nil {
		if afterCursor != nil {
			// we don't need to do total - 1 because of out.Offset + 1
			hasNextPage = (offset + len(items)) < *total
		} else {
			hasNextPage = (offset + len(items)) < *total-1
		}
	}

	page.PageInfo = relay.PageInfo{
		HasNextPage:     hasNextPage,
		HasPreviousPage: hasPreviousPage,
		StartCursor:     startCursor,
		EndCursor:       endCursor,
	}
	page.TotalCount = total

	return page, nil
}
